# -*- coding: utf-8 -*-
"""LF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5oaNMpQMsh2ut1q9gn5MS3znrhl832K
"""

# -*- coding: utf-8 -*-


# ==============================================================================
# IMPORTS (All in one place)
# ==============================================================================
print("="*80 + "\nLoading Libraries...\n" + "="*80)
import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import os
import shutil
import pickle
import re # For robust file parsing
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.axes_grid1.inset_locator import inset_axes
from scipy.interpolate import griddata as _griddata
# *** پوشه نتایج شما ***
# تمام فایل‌ها از اینجا خوانده و در اینجا نوشته می‌شوند
RESULTS_DIR = 'all_my_results'

# Import for Latin Hypercube Sampling (LHS)
try:
    from scipy.stats import qmc
    print("scipy.stats.qmc imported successfully.")
except ImportError:
    print("ERROR: scipy is not installed. Please install it: pip install scipy")
    pass

# --- Global Settings & Seeding for Reproducibility ---
np.random.seed(42)
tf.random.set_seed(42)


# ==============================================================================
# CELL 1: COMPUTATION, MODEL TRAINING, AND DATA SAVING
# ==============================================================================
print("="*80 + "\nSTARTING CELL 1: COMPUTATION, SIMULATION & (500-SAMPLE) TRAINING\n" + "="*80)

# --- SECTION 1.1: Physics Simulation & Data Generation ---

def convert_macleod_xml_to_csv(input_xml_path, output_csv_path):
    """Parses a Macleod .mtx file into a simple, two-column CSV file."""
    try:
        # مسیر فایل ورودی را با پوشه نتایج ترکیب می‌کند
        # *** V14: فرض می‌کنیم فایل‌های .mtx هم در پوشه نتایج هستند ***
        full_input_path = os.path.join(RESULTS_DIR, input_xml_path)
        full_output_path = os.path.join(RESULTS_DIR, output_csv_path)

        if not os.path.exists(full_input_path):
            # اگر در پوشه نتایج نبود، در پوشه اصلی جستجو کن
            full_input_path = input_xml_path
            if not os.path.exists(full_input_path):
                print(f"Input file not found: {input_xml_path}. Skipping conversion.")
                return False

        # اگر فایل خروجی از قبل وجود دارد، تبدیل نکن
        if os.path.exists(full_output_path):
            print(f"Output file '{full_output_path}' already exists. Skipping conversion.")
            return True

        tree = ET.parse(full_input_path)
        root = tree.getroot()
        data_points = []
        for point in root.findall('.//NKPoint'):
            try:
                wavelength = float(point.get('W'))
                n_value = float(point.get('n'))
                data_points.append({'Wavelength': wavelength, 'n': n_value})
            except (ValueError, TypeError):
                continue
        if not data_points: return False
        df = pd.DataFrame(data_points).sort_values(by='Wavelength').reset_index(drop=True)
        df.to_csv(full_output_path, index=False, float_format='%.8f')
        print(f"Successfully converted '{full_input_path}' to '{full_output_path}'")
        return True
    except Exception as e:
        print(f"Error converting {input_xml_path}: {e}")
        return False

def load_material_data(filepath):
    """Loads refractive index data and returns an interpolation function."""
    full_path = os.path.join(RESULTS_DIR, filepath)
    try:
        data = pd.read_csv(full_path)
        return lambda lam: np.interp(lam, data.iloc[:, 0].values, data.iloc[:, 1].values)
    except FileNotFoundError:
        print(f"FATAL ERROR: Material file not found at '{full_path}'. Halting.")
        exit()

def calculate_transmittance(wavelength_range_nm, theta0_deg, thickness_nm, n0_func, n1_func, n2_func):
    """
    Calculates the transmittance spectrum (T = 1 - R) for P-polarization.
    """
    theta0_rad = np.deg2rad(theta0_deg)
    d = thickness_nm * 1e-9
    n0, n1, n2 = n0_func(wavelength_range_nm), n1_func(wavelength_range_nm), n2_func(wavelength_range_nm)

    with np.errstate(invalid='ignore'): # Ignore warnings for complex numbers
        theta1_rad = np.lib.scimath.arcsin((n0 / n1) * np.sin(theta0_rad))
        theta2_rad = np.lib.scimath.arcsin((n1 / n2) * np.sin(theta1_rad))

    r01_p = (n1 * np.cos(theta0_rad) - n0 * np.cos(theta1_rad)) / (n1 * np.cos(theta0_rad) + n0 * np.cos(theta1_rad))
    r12_p = (n2 * np.cos(theta1_rad) - n1 * np.cos(theta2_rad)) / (n2 * np.cos(theta1_rad) + n1 * np.cos(theta2_rad))
    beta = (2 * np.pi / (wavelength_range_nm * 1e-9)) * n1 * d * np.cos(theta1_rad)
    r_total_p = (r01_p + r12_p * np.exp(2j * beta)) / (1 + r01_p * r12_p * np.exp(2j * beta))

    reflectance = np.abs(r_total_p)**2
    reflectance = np.nan_to_num(reflectance) # Replace NaN with 0

    transmittance = 1.0 - reflectance
    return transmittance


def generate_dataset_from_pairs(param_pairs, wavelengths, material_config, data_dir, is_lhs=False):
    """
    Helper function to generate and save a dataset from (angle, thickness) pairs.
    *** MODIFICATION: Does NOT delete existing data. ***
    """
    full_data_dir = os.path.join(RESULTS_DIR, data_dir)
    if not os.path.exists(full_data_dir):
        os.makedirs(full_data_dir)
        print(f"Created directory: '{full_data_dir}/'")
    else:
        print(f"Data directory '{full_data_dir}/' already exists. Verifying files...")

    n_incident_func = lambda lam: np.ones_like(lam)
    n_film_func = load_material_data(material_config['film_csv'])
    n_substrate_func = load_material_data(material_config['substrate_csv'])

    files_created_count = 0
    for i, (angle, thickness) in enumerate(param_pairs):
        if is_lhs:
            filename = f"sample_{i+1:003d}_angle_{angle:.1f}_thickness_{thickness:.1f}.csv"
        else:
            filename = f"angle_{angle:.1f}_thickness_{thickness:.1f}.csv"

        filepath = os.path.join(full_data_dir, filename)

        # *** INCREMENTAL CHECK: Skip if file already exists ***
        if os.path.exists(filepath):
            continue

        transmittance = calculate_transmittance(wavelengths, angle, thickness, n_incident_func, n_film_func, n_substrate_func)
        transmittance_pct = transmittance * 100
        transmittance_error = 100.0 - transmittance_pct

        pd.DataFrame({
            'Wavelength (nm)': wavelengths,
            'P-Transmittance-Error (%)': transmittance_error # Save T_Error
        }).to_csv(filepath, index=False, float_format='%.6f')
        files_created_count += 1

    if files_created_count > 0:
        print(f"Successfully generated {files_created_count} new data files in '{full_data_dir}/'")
    else:
        print(f"All {len(param_pairs)} data files already exist in '{full_data_dir}/'. No new files created.")


def run_physics_simulation_and_data_generation(material_config):
    """
    Finds the true physical *transmittance* optimum and generates all datasets.
    *** MODIFICATION: Skips generation if files exist. ***
    """
    print("\n" + "="*80 + f"\nSECTION 1.1: PHYSICS SIMULATION FOR: {material_config['name']}\n" + "="*80)

    wavelengths = np.arange(400, 1201, 1) # This defines the output shape: 801
    n_incident_func = lambda lam: np.ones_like(lam)
    n_film_func = load_material_data(material_config['film_csv'])
    n_substrate_func = load_material_data(material_config['substrate_csv'])

    true_opt_filepath = os.path.join(RESULTS_DIR, f"{material_config['prefix']}_true_optimal_spectrum.csv")

    if not os.path.exists(true_opt_filepath):
        print("\n--- Searching for True Physical Optimum (Max Transmittance) ---")
        search_angles_fine, search_thicknesses_fine = np.arange(0, 61, 1), np.arange(30, 151, 1)
        best_max_transmittance = float('-inf')
        best_angle, best_thickness = -1, -1

        for angle in search_angles_fine:
            for thickness in search_thicknesses_fine:
                p_transmittance = calculate_transmittance(wavelengths, angle, thickness, n_incident_func, n_film_func, n_substrate_func)
                current_max_transmittance = np.max(p_transmittance)
                if current_max_transmittance > best_max_transmittance:
                    best_max_transmittance, best_angle, best_thickness = current_max_transmittance, angle, thickness

        print(f"True Optimum Found: Angle={best_angle}°, Thickness={best_thickness} nm")
        material_config['true_optimum'] = {'angle': best_angle, 'thickness': best_thickness}

        final_optimal_spectrum_T = calculate_transmittance(wavelengths, best_angle, best_thickness, n_incident_func, n_film_func, n_substrate_func)
        pd.DataFrame({
            'Wavelength (nm)': wavelengths,
            'True Transmittance (%)': final_optimal_spectrum_T * 100,
            'True Transmittance-Error (%)': 100.0 - (final_optimal_spectrum_T * 100)
        }).to_csv(true_opt_filepath, index=False)
    else:
        print("\n--- True Physical Optimum file found. Skipping search. ---")
        if material_config['prefix'] == 'mgf2':
            material_config['true_optimum'] = {'angle': 51.0, 'thickness': 148.0}
        elif material_config['prefix'] == 'sio2':
            material_config['true_optimum'] = {'angle': 54.0, 'thickness': 150.0}

    print("\n--- Verifying 500-sample dataset (LHS) ---")
    sampler = qmc.LatinHypercube(d=2, seed=42)
    samples = sampler.random(n=500)
    l_bounds = [0, 30]  # Angle: [0, 60], Thickness: [30, 150]
    u_bounds = [60, 150]
    scaled_samples = qmc.scale(samples, l_bounds, u_bounds)
    dl_param_pairs = np.round(scaled_samples, 1)
    generate_dataset_from_pairs(dl_param_pairs, wavelengths, material_config, f"{material_config['prefix']}_data", is_lhs=True)

    print("\n--- Verifying 56-sample dataset (OOD) ---")
    ood_angles = [2.5, 7.5, 12.5, 17.5, 22.5, 27.5, 32.5] # 7 angles
    ood_thicknesses = np.arange(35, 146, 15).astype(float) # 8 thicknesses
    ood_param_pairs = [(a, t) for a in ood_angles for t in ood_thicknesses] # 7 * 8 = 56 samples
    generate_dataset_from_pairs(ood_param_pairs, wavelengths, material_config, f"{material_config['prefix']}_ood_data", is_lhs=False)

    return wavelengths

# --- SECTION 1.2: Deep Learning Definition ---

def load_dl_data_from_dir(data_dir):
    """
    Helper to load datasets from their directories using REGEX.
    *** Reads P-Transmittance-Error (%) column. ***
    """
    full_data_dir = os.path.join(RESULTS_DIR, data_dir)
    X_list, Y_list, wavelengths_data = [], [], None
    if not os.path.exists(full_data_dir):
        print(f"Warning: Data directory not found: {full_data_dir}")
        return None, None, None

    print(f"Loading data from: {full_data_dir}")

    sample_pattern = re.compile(r"sample_(\d+)_angle_(-?[\d\.]+)_thickness_(-?[\d\.]+)\.csv")
    angle_pattern = re.compile(r"angle_(-?[\d\.]+)_thickness_(-?[\d\.]+)\.csv")

    for filename in os.listdir(full_data_dir):
        angle, thickness = None, None
        match = sample_pattern.match(filename)
        if match:
            angle, thickness = float(match.group(2)), float(match.group(3))
        else:
            match = angle_pattern.match(filename)
            if match:
                angle, thickness = float(match.group(1)), float(match.group(2))
            else:
                continue

        try:
            df = pd.read_csv(os.path.join(full_data_dir, filename))
            # *** CHANGED COLUMN ***
            Y_list.append(df['P-Transmittance-Error (%)'].values)
            X_list.append([angle, thickness])
            if wavelengths_data is None: wavelengths_data = df['Wavelength (nm)'].values
        except Exception as e:
            print(f"Warning: Could not read file {filename}: {e}")

    print(f"Loaded {len(X_list)} samples.")
    if len(X_list) == 0:
         print(f"CRITICAL WARNING: No files were loaded. Check file naming convention in '{full_data_dir}'!")

    return np.array(X_list, dtype=np.float32), np.array(Y_list, dtype=np.float32), wavelengths_data

# *** UPGRADE V9: Fixed focused loss (FOR MINIMIZATION) ***
def create_focused_loss(shape_weight, min_value_weight, min_location_weight):
    """
    Creates the original 3-component loss function (Shape, Value, Location)
    to MINIMIZE the Transmittance-Error.
    *** V9: Fixed by scaling the location_loss component. ***
    """
    def focused_loss(y_true, y_pred): # y_true is now T_Error
        epsilon = 1e-7

        # 1. Shape Loss: Weight = 1 / (T_Error + eps)
        y_true_safe = tf.maximum(y_true, epsilon)
        shape_weights = tf.math.divide_no_nan(1.0, y_true_safe)
        shape_loss = tf.reduce_mean(shape_weights * tf.square(y_true - y_pred))

        # 2. Min Value Loss (finds the minimum T_Error)
        min_true_val = tf.reduce_min(y_true, axis=-1)
        min_pred_val = tf.reduce_min(y_pred, axis=-1)
        min_value_loss = tf.reduce_mean(tf.square(min_true_val - min_pred_val))

        # 3. Min Location Loss (finds location of minimum T_Error)
        min_true_idx = tf.argmin(y_true, axis=-1)
        min_pred_idx = tf.argmin(y_pred, axis=-1)

        # *** V9 FIX: Scale the location loss ***
        # The indices range from 0 to 800. The squared error can be up to 800^2.
        # We must scale this error to be on the same order of magnitude as the other losses.
        # Wavelengths are 400 to 1200 nm (801 points).
        location_loss_scaler = tf.constant(801.0**2, dtype=tf.float32)

        min_location_loss = tf.reduce_mean(tf.square(
            tf.cast(min_true_idx, tf.float32) - tf.cast(min_pred_idx, tf.float32)
        )) / location_loss_scaler # <-- Divide by scaler

        total_loss = (shape_weight * shape_loss) + \
                     (min_value_weight * min_value_loss) + \
                     (min_location_weight * min_location_loss)
        return total_loss

    loss_name = f'focused_s{int(shape_weight*100)}_v{int(min_value_weight*100)}_l{int(min_location_weight*100)}'
    focused_loss.__name__ = loss_name
    return focused_loss

def spectral_angle_mapper_loss(y_true, y_pred):
    """
    Creates the Spectral Angle Mapper (SAM) loss function.
    """
    epsilon = 1e-7
    y_true_norm = tf.norm(y_true, axis=-1)
    y_pred_norm = tf.norm(y_pred, axis=-1)
    dot_product = tf.reduce_sum(y_true * y_pred, axis=-1)

    denominator = y_true_norm * y_pred_norm + epsilon
    cosine_similarity = dot_product / denominator

    cosine_similarity = tf.clip_by_value(cosine_similarity, -1.0 + epsilon, 1.0 - epsilon)
    sam_rad = tf.acos(cosine_similarity)
    return tf.reduce_mean(sam_rad)
spectral_angle_mapper_loss.__name__ = 'sam_loss'

# *** UPGRADE V11: Reverted to simple, proven V8 architecture. Removed BatchNormalization. ***
def create_dl_model(input_shape, output_shape):
    """
    Defines the robust MLP model with GaussianNoise.
    (V8 architecture, proven to be stable and effective).
    """
    return keras.Sequential([
        layers.Input(shape=input_shape),
        layers.GaussianNoise(0.02),
        layers.Dense(128, activation='relu'),
        layers.Dense(256, activation='relu'),
        layers.Dense(256, activation='relu'),
        layers.Dense(output_shape, activation='linear'), # Linear first
        layers.ReLU(max_value=100.0) # Then ReLU clip for [0, 100] T_Error
    ])

def run_single_dl_experiment(config, X_train, y_train, X_val, y_val, scaler, wavelengths, material_config):
    """
    Runs one full training and evaluation cycle on T_Error.
    *** V14: Skips training if model file already exists in RESULTS_DIR. ***
    """
    config_name = config['name']
    loss_function = config['loss']

    # *** V14: All paths point to RESULTS_DIR ***
    model_filename = os.path.join(RESULTS_DIR, f"{material_config['prefix']}_model_{config_name}.h5")

    # *** INCREMENTAL CHECK: Skip if model file already exists ***
    if os.path.exists(model_filename):
        print("\n" + "-"*60 + f"\nSkipping training for: {config_name} ({material_config['name']}) - Model file already exists.\n" + "-"*60)
        return # Skip this training entirely

    print("\n" + "-"*60 + f"\nRunning DL Experiment: {config_name} ({material_config['name']})\n" + "-"*60)

    y_train_target = y_train
    y_val_target = y_val

    model = create_dl_model(input_shape=(X_train.shape[1],), output_shape=y_train_target.shape[1])

    model.compile(optimizer=keras.optimizers.Adam(learning_rate=5e-4), loss=loss_function)

    history_filename = os.path.join(RESULTS_DIR, f"{material_config['prefix']}_{config_name}_history.csv")

    callbacks = [
        EarlyStopping(monitor='val_loss', patience=100, restore_best_weights=True, verbose=1, min_delta=1e-3),
        ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=40, min_lr=1e-7, verbose=1),
        ModelCheckpoint(model_filename, save_best_only=True, monitor='val_loss')
    ]

    history = model.fit(
        X_train, y_train_target,
        validation_data=(X_val, y_val_target),
        epochs=800, # 800 is still good, EarlyStopping will handle it
        batch_size=4,
        callbacks=[callbacks],
        verbose=1
    )
    print(f"Training complete for {config_name}. Best val_loss: {np.min(history.history['val_loss']):.4f}")

    # V9: Save history for ALL models, not just one
    pd.DataFrame(history.history).to_csv(history_filename, index=False)
    print(f"Saved training history to {history_filename}")

    custom_objects = {} if isinstance(loss_function, str) else {loss_function.__name__: loss_function}
    if os.path.exists(model_filename):
        best_model = keras.models.load_model(model_filename, custom_objects=custom_objects)
        print(f"Loaded best model from {model_filename}")
    else:
        print(f"Warning: Model file {model_filename} not found after training. Using last state model.")
        best_model = model

    search_grid = np.array([[a, t] for a in np.arange(0, 61, 1) for t in np.arange(30, 151, 1)])

    # Model predicts T_Error
    predicted_error_spectra = best_model.predict(scaler.transform(search_grid), verbose=0)

    # Convert back to Transmittance for saving and analysis
    predicted_T_spectra = 100.0 - predicted_error_spectra
    predicted_T_spectra = np.clip(predicted_T_spectra, 0.0, 100.0) # Final safety clip

    # Find the spectrum with the highest peak transmittance
    optimal_spectrum_idx = np.argmax(np.max(predicted_T_spectra, axis=1))
    optimal_spectrum = predicted_T_spectra[optimal_spectrum_idx]

    pd.DataFrame({
        'Wavelength (nm)': wavelengths,
        'Predicted Transmittance (%)': optimal_spectrum
    }).to_csv(os.path.join(RESULTS_DIR, f"{material_config['prefix']}_optimal_spectrum_{config_name}.csv"), index=False)


# --- SECTION 1.3: Main Execution Workflow ---

material_pipeline_configs = [
    {'name': 'MgF2 on BK7', 'prefix': 'mgf2', 'film_csv': 'mgf2_base.csv', 'substrate_csv': 'bk7_base.csv'},
    {'name': 'SiO2 on BK7', 'prefix': 'sio2', 'film_csv': 'sio2_base.csv', 'substrate_csv': 'bk7_base.csv'}
]

# *** V14: This list contains ALL 8 models for the final paper ***
# The script will SKIP training for any model that already has an .h5 file in RESULTS_DIR
loss_configs = [
    # --- Our Proposed Models (The "Story") ---
    # 1. The new "Hero" model, designed to beat shape_only (R1C5)
    {'name': 'PROPOSED_Shape+Location_v2', 'loss': create_focused_loss(shape_weight=0.95, min_value_weight=0.0, min_location_weight=0.05)},
    # 2. The original "focused" models (from v12)
    {'name': 'focused_s80_v10_l10', 'loss': create_focused_loss(shape_weight=0.8, min_value_weight=0.1, min_location_weight=0.1)},
    {'name': 'focused_s90_v05_l05', 'loss': create_focused_loss(shape_weight=0.9, min_value_weight=0.05, min_location_weight=0.05)},
    {'name': 'focused_s50_v25_l25', 'loss': create_focused_loss(shape_weight=0.5, min_value_weight=0.25, min_location_weight=0.25)},

    # --- Baseline Models (The "Competition") ---
    # 3. The main competitor (from v11)
    {'name': 'baseline_shape_only', 'loss': create_focused_loss(shape_weight=1.0, min_value_weight=0.0, min_location_weight=0.0)},
    # 4. The reviewer requests (R1C1 & R2C3)
    {'name': 'baseline_mse', 'loss': 'mean_squared_error'},
    {'name': 'baseline_l1_mae', 'loss': 'mean_absolute_error'},
    {'name': 'baseline_sam', 'loss': spectral_angle_mapper_loss},
]

# This list must contain ALL custom loss objects for loading models in CELL 2
all_custom_objects = {
    'focused_s95_v0_l5': create_focused_loss(0.95, 0.0, 0.05), # مدل "قهرمان" جدید
    'focused_s80_v10_l10': create_focused_loss(0.8, 0.1, 0.1),
    'focused_s90_v05_l05': create_focused_loss(0.9, 0.05, 0.05),
    'focused_s50_v25_l25': create_focused_loss(0.5, 0.25, 0.25),
    'focused_s100_v0_l0': create_focused_loss(1.0, 0.0, 0.0), # This is baseline_shape_only
    'sam_loss': spectral_angle_mapper_loss
}

# --- Run CELL 1 ---
if __name__ == "__main__":

    # اطمینان از وجود پوشه نتایج
    if not os.path.exists(RESULTS_DIR):
        os.makedirs(RESULTS_DIR)
        print(f"Created results directory: {RESULTS_DIR}")

    materials_to_convert = {'si.mtx': 'sio2_base.csv', 'glass.mtx': 'bk7_base.csv', 'mg.mtx': 'mgf2_base.csv'}
    for infile, outfile in materials_to_convert.items():
        # فایل mtx را در پوشه اصلی چک می‌کند، اما فایل csv را در پوشه نتایج می‌سازد
        if os.path.exists(infile) and not os.path.exists(os.path.join(RESULTS_DIR, outfile)):
             convert_macleod_xml_to_csv(infile, outfile)

    for material in material_pipeline_configs:
        if not all(os.path.exists(os.path.join(RESULTS_DIR, f)) for f in [material['film_csv'], material['substrate_csv']]):
            print(f"\nFATAL ERROR: Skipping pipeline for {material['name']} because base files are missing.")
            print(f"Please ensure '{material['film_csv']}' and '{material['substrate_csv']}' exist in {RESULTS_DIR}.")
            continue

        wavelengths = run_physics_simulation_and_data_generation(material)

        print("\n" + "="*80 + f"\nSECTION 1.2: DEEP LEARNING EXPERIMENTS FOR: {material['name']}\n" + "="*80)

        X, y, _ = load_dl_data_from_dir(f"{material['prefix']}_data") # y is now T_Error
        if X is None or len(X) == 0:
            print(f"FATAL: No data loaded for {material['name']}. Stopping.")
            continue

        X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)
        print(f"Training with {len(X_train)} samples, validating with {len(X_val)} samples.")

        # *** V14: Load scaler from RESULTS_DIR, or create if it doesn't exist ***
        scaler_path = os.path.join(RESULTS_DIR, f"{material['prefix']}_scaler.pkl")
        scaler = MinMaxScaler() # Create a new scaler object

        if not os.path.exists(scaler_path):
            print(f"Scaler file {scaler_path} not found. Creating and saving a new one...")
            X_train_scaled = scaler.fit_transform(X_train)
            X_val_scaled = scaler.transform(X_val)
            with open(scaler_path, 'wb') as f:
                pickle.dump(scaler, f)
            print(f"New scaler saved to {scaler_path}")
        else:
            print(f"Found existing scaler at {scaler_path}. Loading it...")
            with open(scaler_path, 'rb') as f:
                scaler = pickle.load(f)
            X_train_scaled = scaler.transform(X_train)
            X_val_scaled = scaler.transform(X_val)

        # Train all 8 models (it will skip any that already exist)
        for config in loss_configs:
            run_single_dl_experiment(config, X_train_scaled, y_train, X_val_scaled, y_val, scaler, wavelengths, material)

    print("\n" + "="*80 + "\nCELL 1: COMPUTATION & (500-SAMPLE) TRAINING COMPLETE.\n" + "="*80)


# ==============================================================================
# CELL 2: VISUALIZATION, ANALYSIS, AND REPORTING
# ==============================================================================
print("="*80 + "\nSTARTING CELL 2: VISUALIZATION, ANALYSIS & REPORTING\n" + "="*80)

# ==============================================================================
# SECTION 2.1: COMPREHENSIVE RESULTS TABLE (FOR REVIEWERS)
# ==============================================================================
def create_and_save_results_table(material_config, loss_configs, custom_objects):
    """
    Generates the comprehensive results table for Transmittance Maximization.
    *** V14: Added MAE column ***
    """
    print(f"\nGenerating comprehensive results table for {material_config['name']}...")
    prefix = material_config['prefix']

    scaler_path = os.path.join(RESULTS_DIR, f"{prefix}_scaler.pkl")
    if not os.path.exists(scaler_path):
        print(f"ERROR: Scaler file not found at '{scaler_path}'. Skipping table.")
        return None
    with open(scaler_path, 'rb') as f: scaler = pickle.load(f)

    # y_val_full is T_Error
    X_val_full, y_val_full, _ = load_dl_data_from_dir(f"{prefix}_data")
    if X_val_full is None or len(X_val_full) == 0:
        print(f"ERROR: Main data not found for {prefix}. Skipping table.")
        return None
    _, X_val, _, y_val = train_test_split(X_val_full, y_val_full, test_size=0.2, random_state=42)
    X_val_scaled = scaler.transform(X_val)

    # y_ood is T_Error
    X_ood, y_ood, _ = load_dl_data_from_dir(f"{prefix}_ood_data")
    if X_ood is None or len(X_ood) == 0:
        print(f"WARNING: OOD data not found for {prefix}. Skipping OOD metrics.")
        X_ood_scaled, y_ood = None, None
    else:
        X_ood_scaled = scaler.transform(X_ood)

    results = []
    search_grid = np.array([[a, t] for a in np.arange(0, 61, 1) for t in np.arange(30, 151, 1)])
    search_grid_scaled = scaler.transform(search_grid)

    for config in loss_configs:
        model_path = os.path.join(RESULTS_DIR, f"{prefix}_model_{config['name']}.h5")
        if not os.path.exists(model_path):
            print(f"Warning: Model file '{model_path}' not found. Skipping.")
            continue

        # Handle custom object loading
        loss_name_in_file = config['loss'].__name__ if callable(config['loss']) else config['loss']
        if config['name'] == 'baseline_shape_only':
             loss_name_in_file = 'focused_s100_v0_l0'
        # *** V14: Add new hero model name ***
        elif config['name'] == 'PROPOSED_Shape+Location_v2':
             loss_name_in_file = 'focused_s95_v0_l5'

        current_custom_objects = {k: v for k, v in custom_objects.items() if k == loss_name_in_file}

        model = keras.models.load_model(model_path, custom_objects=current_custom_objects, compile=False)

        # --- 1. Validation Metrics ---
        y_pred_val = model.predict(X_val_scaled, verbose=0)
        r2_val = r2_score(y_val, y_pred_val)
        mse_val = mean_squared_error(y_val, y_pred_val)
        mae_val = mean_absolute_error(y_val, y_pred_val) # MAE اضافه شد

        # --- 2. OOD Metrics ---
        r2_ood, mse_ood, mae_ood = np.nan, np.nan, np.nan
        if X_ood_scaled is not None and y_ood is not None:
            y_pred_ood = model.predict(X_ood_scaled, verbose=0)
            r2_ood = r2_score(y_ood, y_pred_ood)
            mse_ood = mean_squared_error(y_ood, y_pred_ood)
            mae_ood = mean_absolute_error(y_ood, y_pred_ood) # MAE اضافه شد

        # --- 3. Optimization Goals ---
        all_error_spectra = model.predict(search_grid_scaled, verbose=0)
        all_T_spectra = 100.0 - all_error_spectra
        all_T_spectra = np.clip(all_T_spectra, 0.0, 100.0)

        max_transmittances = np.max(all_T_spectra, axis=1)
        avg_transmittances = np.mean(all_T_spectra, axis=1)

        peak_idx = np.argmax(max_transmittances)
        avg_idx = np.argmax(avg_transmittances)

        results.append({
            'Model': config['name'],
            'R² (Val, T_Error)': r2_val,
            'MSE (Val, T_Error)': mse_val,
            'MAE (Val, T_Error)': mae_val, # MAE اضافه شد
            'R² (OOD, T_Error)': r2_ood,
            'MSE (OOD, T_Error)': mse_ood,
            'MAE (OOD, T_Error)': mae_ood, # MAE اضافه شد
            'Peak T (%)': max_transmittances[peak_idx],
            'Peak Angle (°)': search_grid[peak_idx][0],
            'Peak Thick. (nm)': search_grid[peak_idx][1],
            'Avg T (%)': avg_transmittances[avg_idx]
        })

    df = pd.DataFrame(results)
    true_opt = material_config['true_optimum']
    title = f"Performance Comparison: {material_config['name']} (True Optimum: Angle={true_opt['angle']}°, Thickness={true_opt['thickness']}°)"

    fig_height = max(4, 0.5 * len(df) + 1.5)
    fig_width = 22 # عرض بیشتر برای گنجاندن ستون‌های MAE

    fig, ax = plt.subplots(figsize=(fig_width, fig_height)); ax.axis('off')

    cols_ordered = [
        'Model', 'R² (Val, T_Error)', 'MSE (Val, T_Error)', 'MAE (Val, T_Error)',
        'R² (OOD, T_Error)', 'MSE (OOD, T_Error)', 'MAE (OOD, T_Error)',
        'Peak T (%)', 'Peak Angle (°)', 'Peak Thick. (nm)', 'Avg T (%)'
    ]
    cols_to_plot = [col for col in cols_ordered if col in df.columns]
    df_ordered = df[cols_to_plot]

    table_data = df_ordered.map(lambda x: f'{x:.4f}' if isinstance(x, (float, np.float32, np.float64)) else x).values
    table = ax.table(cellText=table_data,
                     colLabels=df_ordered.columns, loc='center', cellLoc='center')

    table.auto_set_font_size(False); table.set_fontsize(9); table.scale(1, 1.8)
    for (i, j), cell in table.get_celld().items():
        cell.set_edgecolor('black')
        if i == 0: cell.set_text_props(weight='bold', color='white'); cell.set_facecolor('#40466e')
        else: cell.set_facecolor(['#f8f9fa', '#e9ecef'][i % 2])

    plt.title(title, weight='bold', fontsize=14, y=0.98 if len(df) > 5 else 0.9)

    output_path = os.path.join(RESULTS_DIR, f"{prefix}_results_comparison_table.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight', pad_inches=0.4)
    plt.close(fig)
    print(f"Results table saved to {output_path}")

    return df


# ==============================================================================
# SECTION 2.2: *** NEW (V10) *** METRIC COMPARISON CHART
# ==============================================================================
def plot_metric_comparison_chart(material_config, results_df):
    """
    Generates a grouped bar chart comparing key R², MSE, and MAE metrics
    across all trained models for publication.
    """
    print(f"Generating metric comparison bar chart for {material_config['name']}...")
    prefix = material_config['prefix']

    # Prepare data for plotting
    df = results_df.set_index('Model')

    # Filter for the metrics we want to plot
    r2_metrics = ['R² (Val, T_Error)', 'R² (OOD, T_Error)']
    mse_metrics = ['MSE (Val, T_Error)', 'MSE (OOD, T_Error)']
    mae_metrics = ['MAE (Val, T_Error)', 'MAE (OOD, T_Error)'] # MAE اضافه شد

    # Get model names and positions
    models = df.index
    x = np.arange(len(models))  # the label locations
    width = 0.25  # عرض بارها کمتر شد تا ۳ تا جا شوند

    plt.style.use('seaborn-v0_8-ticks')
    # اکنون ۳ نمودار داریم
    fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(28, 8)) # عرض کل فیگور بیشتر شد

    # --- Panel 1: R² Scores (Higher is better) ---
    rects1 = ax1.bar(x - width/2, df[r2_metrics[0]], width, label='Validation R²', color='#007bff')
    rects2 = ax1.bar(x + width/2, df[r2_metrics[1]], width, label='OOD R²', color='#ffc107')

    ax1.set_ylabel('R² Score (on T_Error)', fontsize=14, fontweight='bold')
    ax1.set_title(f'R² Score Comparison: {material_config["name"]}', fontsize=16, fontweight='bold')
    ax1.set_xticks(x, models, rotation=60, ha='right', fontsize=12, fontweight='bold')
    ax1.tick_params(axis='y', labelsize=12)
    plt.setp(ax1.get_yticklabels(), fontweight='bold')
    ax1.legend(fontsize=12)
    ax1.grid(True, linestyle='--', axis='y')
    ax1.set_ylim(bottom=max(0.9, df[r2_metrics].min().min(skipna=True) - 0.05), top=1.01) # زوم روی مقادیر بالا
    ax1.bar_label(rects1, padding=3, fmt='%.3f', fontsize=9, rotation=90)
    ax1.bar_label(rects2, padding=3, fmt='%.3f', fontsize=9, rotation=90)

    # --- Panel 2: MSE Scores (Lower is better) ---
    rects3 = ax2.bar(x - width/2, df[mse_metrics[0]], width, label='Validation MSE', color='#28a745')
    rects4 = ax2.bar(x + width/2, df[mse_metrics[1]], width, label='OOD MSE', color='#dc3545')

    ax2.set_ylabel('Mean Squared Error (on T_Error)', fontsize=14, fontweight='bold')
    ax2.set_title(f'MSE Comparison: {material_config["name"]}', fontsize=16, fontweight='bold')
    ax2.set_xticks(x, models, rotation=60, ha='right', fontsize=12, fontweight='bold')
    ax2.tick_params(axis='y', labelsize=12)
    plt.setp(ax2.get_yticklabels(), fontweight='bold')
    ax2.legend(fontsize=12)
    ax2.grid(True, linestyle='--', axis='y')
    ax2.set_yscale('log') # **CRITICAL:** Log scale
    ax2.bar_label(rects3, padding=3, fmt='%.4f', fontsize=9, rotation=90)
    ax2.bar_label(rects4, padding=3, fmt='%.4f', fontsize=9, rotation=90)

    # --- Panel 3: MAE Scores (Lower is better) ---
    rects5 = ax3.bar(x - width/2, df[mae_metrics[0]], width, label='Validation MAE', color='#17a2b8')
    rects6 = ax3.bar(x + width/2, df[mae_metrics[1]], width, label='OOD MAE', color='#fd7e14')

    ax3.set_ylabel('Mean Absolute Error (on T_Error)', fontsize=14, fontweight='bold')
    ax3.set_title(f'MAE (L1) Comparison: {material_config["name"]}', fontsize=16, fontweight='bold')
    ax3.set_xticks(x, models, rotation=60, ha='right', fontsize=12, fontweight='bold')
    ax3.tick_params(axis='y', labelsize=12)
    plt.setp(ax3.get_yticklabels(), fontweight='bold')
    ax3.legend(fontsize=12)
    ax3.grid(True, linestyle='--', axis='y')
    ax3.set_yscale('log') # **CRITICAL:** Log scale
    ax3.bar_label(rects5, padding=3, fmt='%.4f', fontsize=9, rotation=90)
    ax3.bar_label(rects6, padding=3, fmt='%.4f', fontsize=9, rotation=90)

    fig.suptitle(f'Model Metric Comparison for {material_config["name"]}', fontsize=20, fontweight='bold', y=1.08)
    plt.tight_layout(pad=1.0, rect=[0, 0, 1, 1]) # Adjust layout

    output_path = os.path.join(RESULTS_DIR, f"{prefix}_metric_comparison_chart.png")
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close(fig)
    print(f"Metric comparison chart saved to {output_path}")


# ==============================================================================
# SECTION 2.3: DETAILED VISUALIZATION SUITE
# ==============================================================================
def generate_detailed_visualizations(material_config, custom_objects, best_model_name):
    """
    Generates the 3D plots, contour, learning curve, and scatter plot
    for the *dynamically selected best model* from CELL 1.
    """
    prefix = material_config['prefix']

    model_path = os.path.join(RESULTS_DIR, f"{prefix}_model_{best_model_name}.h5")
    history_path = os.path.join(RESULTS_DIR, f"{prefix}_{best_model_name}_history.csv")
    scaler_path = os.path.join(RESULTS_DIR, f"{prefix}_scaler.pkl")

    best_model_name_pretty = best_model_name.replace("_", " ").title()

    if not all(os.path.exists(p) for p in [model_path, history_path, scaler_path]):
        print(f"Warning: Missing files for detailed visualization of {prefix} using model {best_model_name}. Skipping.")
        print(f"Missing: {model_path if not os.path.exists(model_path) else ''} {history_path if not os.path.exists(history_path) else ''}")
        return

    print(f"\nGenerating detailed visualization suite for {prefix} (using Best Model: {best_model_name})...")

    # --- Load Artifacts ---
    loss_name_in_file = best_model_name
    if best_model_name == 'baseline_shape_only':
         loss_name_in_file = 'focused_s100_v0_l0'
    elif best_model_name == 'baseline_sam':
         loss_name_in_file = 'sam_loss'
    # *** V14: Add new hero model name ***
    elif best_model_name == 'PROPOSED_Shape+Location_v2':
         loss_name_in_file = 'focused_s95_v0_l5'

    current_custom_objects = {k: v for k, v in custom_objects.items() if k == loss_name_in_file}

    model = keras.models.load_model(model_path, custom_objects=current_custom_objects, compile=False)
    with open(scaler_path, 'rb') as f: scaler = pickle.load(f)
    history_df = pd.read_csv(history_path)

    X, y, wavelengths = load_dl_data_from_dir(f"{prefix}_data") # y is T_Error
    if X is None or len(X) == 0:
        print(f"ERROR: Main data not found for {prefix}. Skipping detailed plots.")
        return
    _, X_test, _, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # y_test is T_Error
    X_test_scaled = scaler.transform(X_test)
    y_pred = model.predict(X_test_scaled, verbose=0) # y_pred is T_Error

    # --- Print Numerical Results (as in user's sample) ---
    print(f"\n--- Evaluation for Best Model ({best_model_name_pretty}) ({prefix} - Validation Set) ---")
    print(f"(Metrics below are on T_Error, lower is better)")
    print(f"R² Score (on T_Error): {r2_score(y_test, y_pred):.4f}")
    print(f"Mean Squared Error (on T_Error): {mean_squared_error(y_test, y_pred):.4f}")
    print(f"Mean Absolute Error (on T_Error): {mean_absolute_error(y_test, y_pred):.4f}")

    # --- Find Optima for Plotting (by converting back to T) ---
    search_grid = np.array([[a, t] for a in np.arange(0, 61, 1) for t in np.arange(30, 151, 1)])
    search_grid_scaled = scaler.transform(search_grid)
    all_error_spectra = model.predict(search_grid_scaled, verbose=0)
    all_T_spectra = 100.0 - all_error_spectra
    all_T_spectra = np.clip(all_T_spectra, 0.0, 100.0) # Safety clip

    max_transmittances = np.max(all_T_spectra, axis=1)
    avg_transmittances = np.mean(all_T_spectra, axis=1)

    peak_opt_idx = np.argmax(max_transmittances)
    peak_opt_val = max_transmittances[peak_opt_idx]
    peak_opt_angle, peak_opt_thick = search_grid[peak_opt_idx]
    peak_opt_spec = all_T_spectra[peak_opt_idx] # Use converted T spectrum
    peak_opt_wave = wavelengths[np.argmax(peak_opt_spec)]

    avg_opt_idx = np.argmax(avg_transmittances)
    avg_opt_val = avg_transmittances[avg_opt_idx]
    avg_opt_angle, avg_opt_thick = search_grid[avg_opt_idx]

    print(f"\n--- OPTIMIZATION RESULTS ({best_model_name_pretty} Model) ---")
    print("\nGoal 1: Best PEAK Performance (Highest single point)")
    print(f"   - Highest Transmittance: {peak_opt_val:.4f}%")
    print(f"   - At Angle: {peak_opt_angle:.0f} deg, Thickness: {peak_opt_thick:.0f} nm")
    print(f"   - At Wavelength: {peak_opt_wave:.0f} nm")
    print("\nGoal 2: Best OVERALL Performance (Highest average)")
    print(f"   - Highest Average Transmittance: {avg_opt_val:.4f}%")
    print(f"   - At Angle: {avg_opt_angle:.0f} deg, Thickness: {avg_opt_thick:.0f} nm")

    # --- Plot 1A: Effect of Thickness ---
    fig1 = plt.figure(figsize=(8, 6)); ax1 = fig1.add_subplot(111, projection='3d')
    t_range = np.arange(30, 151, 2)
    fixed_angle_error_spectra = model.predict(scaler.transform(np.array([[peak_opt_angle, t] for t in t_range])), verbose=0)
    fixed_angle_T_spectra = 100.0 - fixed_angle_error_spectra
    T, W = np.meshgrid(t_range, wavelengths)
    ax1.plot_surface(T, W, fixed_angle_T_spectra.T, cmap='hot', edgecolor='none')
    ax1.set_xlabel('Thickness (nm)', fontsize=16, fontweight='bold', labelpad=5)
    ax1.set_ylabel('Wavelength (nm)', fontsize=16, fontweight='bold', labelpad=8)
    ax1.set_zlabel('Transmittance (%)', fontsize=16, fontweight='bold', labelpad=20)
    ax1.tick_params(axis='x', labelsize=14); ax1.tick_params(axis='y', labelsize=14); ax1.tick_params(axis='z', labelsize=14)
    plt.setp(ax1.get_xticklabels(), fontweight='bold'); plt.setp(ax1.get_yticklabels(), fontweight='bold'); plt.setp(ax1.get_zticklabels(), fontweight='bold')
    plt.tight_layout(pad=1.0); plt.savefig(os.path.join(RESULTS_DIR, f'{prefix}_3D_Thickness_Effect.jpg'), dpi=300); plt.close(fig1)

    # --- Plot 1B: Effect of Angle ---
    fig2 = plt.figure(figsize=(8, 6)); ax2 = fig2.add_subplot(111, projection='3d')
    a_range = np.arange(0, 61, 2)
    fixed_thick_error_spectra = model.predict(scaler.transform(np.array([[a, peak_opt_thick] for a in a_range])), verbose=0)
    fixed_thick_T_spectra = 100.0 - fixed_thick_error_spectra
    A, W = np.meshgrid(a_range, wavelengths)
    ax2.plot_surface(A, W, fixed_thick_T_spectra.T, cmap='hot', edgecolor='none')
    ax2.set_xlabel('Angle (degrees)', fontsize=16, fontweight='bold', labelpad=5)
    ax2.set_ylabel('Wavelength (nm)', fontsize=16, fontweight='bold', labelpad=8)
    ax2.set_zlabel('Transmittance (%)', fontsize=16, fontweight='bold', labelpad=20)
    ax2.tick_params(axis='x', labelsize=14); ax2.tick_params(axis='y', labelsize=14); ax2.tick_params(axis='z', labelsize=14)
    plt.setp(ax2.get_xticklabels(), fontweight='bold'); plt.setp(ax2.get_yticklabels(), fontweight='bold'); plt.setp(ax2.get_zticklabels(), fontweight='bold')
    plt.tight_layout(pad=1.0); plt.savefig(os.path.join(RESULTS_DIR, f'{prefix}_3D_Angle_Effect.jpg'), dpi=300); plt.close(fig2)

    # --- Plot 2: Contour Plot ---
    fig_c = plt.figure(figsize=(8, 7)); ax_c = fig_c.add_subplot(111)
    contour = ax_c.tricontourf(search_grid[:, 0], search_grid[:, 1], max_transmittances, cmap='hot', levels=20)
    cbar = plt.colorbar(contour, orientation='horizontal', location='bottom', pad=0.2, fraction=0.046, aspect=20)
    cbar.set_label('Predicted Max Transmittance (%)', fontsize=14, fontweight='bold')
    cbar.ax.tick_params(labelsize=14); plt.setp(cbar.ax.get_xticklabels(), fontweight='bold')
    ax_c.scatter(peak_opt_angle, peak_opt_thick, marker='o', color='white', edgecolor='black', s=100, zorder=5, label='Optimum')
    ax_c.set_xlabel('Angle (degrees)', fontsize=14, fontweight='bold'); ax_c.set_ylabel('Thickness (nm)', fontsize=14, fontweight='bold')
    ax_c.set_title(f"Transmittance Landscape ({best_model_name_pretty})", fontsize=18, fontweight='bold')
    ax_c.tick_params(axis='both', labelsize=14); plt.setp(ax_c.get_xticklabels(), fontweight='bold'); plt.setp(ax_c.get_yticklabels(), fontweight='bold')
    ax_c.legend(); plt.savefig(os.path.join(RESULTS_DIR, f'{prefix}_Contour_Plot.jpg'), dpi=300, bbox_inches='tight'); plt.close(fig_c)

    # --- Plot 3: Learning Curve with Inset ---
    fig_lc = plt.figure(figsize=(10, 6)); ax_lc = fig_lc.add_subplot(111)
    ax_lc.plot(history_df['loss'], label='Training Loss')
    ax_lc.plot(history_df['val_loss'], label='Validation Loss')
    min_val_loss = np.min(history_df['val_loss'])
    ax_lc.axhline(y=min_val_loss, color='gray', linestyle='--', label=f'Min Val Loss = {min_val_loss:.4f}')
    ax_lc.set_title(f'Learning Curve ({best_model_name_pretty} Model)', fontsize=18, fontweight='bold'); ax_lc.set_xlabel('Epochs', fontsize=14, fontweight='bold'); ax_lc.set_ylabel('Loss (log scale)', fontsize=14, fontweight='bold')
    ax_lc.legend(loc='upper right', fontsize=12); ax_lc.grid(True, linestyle='--')
    ax_lc.set_yscale('log')
    ax_lc.tick_params(axis='both', labelsize=14); plt.setp(ax_lc.get_xticklabels(), fontweight='bold'); plt.setp(ax_lc.get_yticklabels(), fontweight='bold')

    final_loss = history_df['loss'].iloc[-1]
    final_val_loss = history_df['val_loss'].iloc[-1]
    inset_loc = 'lower left' if (len(history_df) > 50 and final_loss > final_val_loss and final_loss > min_val_loss*2) else 'upper right'

    ax_in = inset_axes(ax_lc, width="50%", height="50%", loc=inset_loc, borderpad=1.5)
    start = max(0, len(history_df) - 50)
    inset_epochs = np.arange(start, len(history_df))
    ax_in.plot(inset_epochs, history_df['loss'][start:], marker='v')
    ax_in.plot(inset_epochs, history_df['val_loss'][start:], marker='*')
    ax_in.set_title('Zoom: Last 50 Epochs', fontweight='bold'); ax_in.set_xlabel('Epochs', fontsize=12); ax_in.set_ylabel('Loss', fontsize=12)
    ax_in.grid(True, linestyle=':'); ax_in.tick_params(axis='both', labelsize=11);
    plt.setp(ax_in.get_xticklabels(), fontweight='bold'); plt.setp(ax_in.get_yticklabels(), fontweight='bold')
    plt.savefig(os.path.join(RESULTS_DIR, f'{prefix}_Learning_Curve.jpg'), dpi=300, bbox_inches='tight'); plt.close(fig_lc)

    # --- Plot 4: Scatter Plot with Inset ---
    y_test_T = 100.0 - y_test
    y_pred_T = 100.0 - y_pred
    fig_s = plt.figure(figsize=(10, 8)); ax_s = fig_s.add_subplot(111)
    y_test_flat, y_pred_flat = y_test_T.flatten(), y_pred_T.flatten()

    scatter = ax_s.scatter(y_test_flat, y_pred_flat, s=5, alpha=0.6, c=y_test_flat, cmap='viridis')
    cbar = plt.colorbar(scatter); cbar.set_label('Actual Transmittance (%)', fontsize=14, fontweight='bold')
    cbar.ax.tick_params(labelsize=14); plt.setp(cbar.ax.get_yticklabels(), fontweight='bold')

    min_lim = max(80, min(y_test_flat.min(), y_pred_flat.min()) - 1)
    max_lim = 100.1
    lims = [min_lim, max_lim]
    ax_s.plot(lims, lims, 'k--', lw=2, label='Ideal Fit')
    ax_s.set_title(f'Actual vs. Predicted Transmittance ({best_model_name_pretty} Model)', fontsize=18, fontweight='bold')
    ax_s.set_xlabel('Actual Transmittance (%)', fontsize=16, fontweight='bold')
    ax_s.set_ylabel('Predicted Transmittance (%)', fontsize=16, fontweight='bold')
    ax_s.grid(True, linestyle='--'); ax_s.legend(loc='upper left', fontsize=12); ax_s.set_xlim(lims); ax_s.set_ylim(lims)
    ax_s.tick_params(axis='both', labelsize=14); plt.setp(ax_s.get_xticklabels(), fontweight='bold'); plt.setp(ax_s.get_yticklabels(), fontweight='bold')

    ax_is = inset_axes(ax_s, width="40%", height="40%", loc='lower right')
    ax_is.scatter(y_test_flat, y_pred_flat, s=6, alpha=0.6, c=y_test_flat, cmap='viridis'); ax_is.plot([99, 100], [99, 100], 'k--', lw=1)
    ax_is.set_xlim(99, 100.05); ax_is.set_ylim(99, 100.05) # Zoom to 99-100
    ax_is.text(0.5, 0.9, 'Zoom: 99–100% Region', ha='center', transform=ax_is.transAxes, fontsize=14, fontweight='bold')
    ax_is.set_xlabel('Actual (%)', fontsize=12); ax_is.set_ylabel('Predicted (%)', fontsize=12)
    ax_is.yaxis.tick_right(); ax_is.yaxis.set_label_position("right")
    ax_is.tick_params(axis='both', labelsize=11); plt.setp(ax_is.get_xticklabels(), fontweight='bold'); plt.setp(ax_is.get_yticklabels(), fontweight='bold')

    plt.savefig(os.path.join(RESULTS_DIR, f'{prefix}_Actual_vs_Predicted_Scatter.jpg'), dpi=300, bbox_inches='tight'); plt.close(fig_s)
    print(f"Detailed visualizations saved for {prefix}.")

# ==============================================================================
# SECTION 2.4: FINAL COMPARISON PLOT (FOR REVIEWERS)
# ==============================================================================
def plot_final_comparison(material_config, loss_configs):
    """
    Generates the final multi-model spectral comparison plot for Transmittance.
    """
    print(f"\nGenerating final multi-model comparison plot for {material_config['name']}...")
    prefix = material_config['prefix']

    plt.style.use('seaborn-v0_8-ticks'); fig, ax = plt.subplots(figsize=(12, 8))

    true_opt_file = os.path.join(RESULTS_DIR, f"{prefix}_true_optimal_spectrum.csv")
    if not os.path.exists(true_opt_file):
        print(f"ERROR: Cannot plot comparison. Missing {true_opt_file}")
        return

    true_opt_df = pd.read_csv(true_opt_file)
    ax.plot(true_opt_df['Wavelength (nm)'], true_opt_df['True Transmittance (%)'], label='True Optimum (Calculated)', color='black', lw=3.5, zorder=10, marker='*', markevery=100, markersize=10)

    cmap = plt.colormaps.get_cmap('tab10')

    for i, config in enumerate(loss_configs):
        spec_file = os.path.join(RESULTS_DIR, f"{prefix}_optimal_spectrum_{config['name']}.csv")
        if os.path.exists(spec_file):
            df = pd.read_csv(spec_file)
            ax.plot(df['Wavelength (nm)'], df['Predicted Transmittance (%)'], label=config['name'], color=cmap(i), linestyle='--', lw=2.5)
        else:
            print(f"Warning: Missing spectrum file {spec_file} for final plot.")

    ax.set_title(f'Optimal Transmittance Spectra Comparison for {material_config["name"]}', fontsize=18, fontweight='bold')
    ax.set_xlabel('Wavelength (nm)', fontsize=14, fontweight='bold'); ax.set_ylabel('Transmittance (%)', fontsize=14, fontweight='bold')
    ax.set_ylim(bottom=95, top=100.1); ax.set_xlim(400, 1200) # Focus on the 95-100% region
    ax.legend(fontsize=11); ax.grid(True, linestyle='--')
    plt.tight_layout()

    output_path = os.path.join(RESULTS_DIR, f"{prefix}_publication_comparison_plot.png")
    plt.savefig(output_path, dpi=300); plt.close(fig)
    print(f"Final comparison plot saved to {output_path}")

# ==============================================================================
# MAIN EXECUTION BLOCK (CELL 2)
# ==============================================================================
if __name__ == "__main__":

    # *** V14: This list must contain ALL 8 models we want to compare ***
    all_loss_configs_for_reporting = [
        # --- Our Proposed Models (The "Story") ---
        # 1. The new "Hero" model, designed to beat shape_only (R1C5)
        {'name': 'PROPOSED_Shape+Location_v2', 'loss': create_focused_loss(shape_weight=0.95, min_value_weight=0.0, min_location_weight=0.05)},
        # 2. The original "focused" models (from v12)
        {'name': 'focused_s80_v10_l10', 'loss': create_focused_loss(shape_weight=0.8, min_value_weight=0.1, min_location_weight=0.1)},
        {'name': 'focused_s90_v05_l05', 'loss': create_focused_loss(shape_weight=0.9, min_value_weight=0.05, min_location_weight=0.05)},
        {'name': 'focused_s50_v25_l25', 'loss': create_focused_loss(shape_weight=0.5, min_value_weight=0.25, min_location_weight=0.25)},

        # --- Baseline Models (The "Competition") ---
        # 3. The main competitor (from v11)
        {'name': 'baseline_shape_only', 'loss': create_focused_loss(shape_weight=1.0, min_value_weight=0.0, min_location_weight=0.0)},
        # 4. The reviewer requests (R1C1 & R2C3)
        {'name': 'baseline_mse', 'loss': 'mean_squared_error'},
        {'name': 'baseline_l1_mae', 'loss': 'mean_absolute_error'},
        {'name': 'baseline_sam', 'loss': spectral_angle_mapper_loss},
    ]

    all_custom_objects_for_reporting = {
        'focused_s95_v0_l5': create_focused_loss(0.95, 0.0, 0.05), # مدل "قهرمان" جدید
        'focused_s80_v10_l10': create_focused_loss(0.8, 0.1, 0.1),
        'focused_s90_v05_l05': create_focused_loss(0.9, 0.05, 0.05),
        'focused_s50_v25_l25': create_focused_loss(0.5, 0.25, 0.25),
        'focused_s100_v0_l0': create_focused_loss(1.0, 0.0, 0.0), # baseline_shape_only
        'sam_loss': spectral_angle_mapper_loss
    }

    all_material_configs = [
        {'name': 'MgF2 on BK7', 'prefix': 'mgf2', 'film_csv': 'mgf2_base.csv', 'substrate_csv': 'bk7_base.csv'},
        {'name': 'SiO2 on BK7', 'prefix': 'sio2', 'film_csv': 'sio2_base.csv', 'substrate_csv': 'bk7_base.csv'}
    ]

    # This loop runs *after* CELL 1 is complete.
    for material in all_material_configs:
        print("\n" + "#"*80 + f"\nVISUALIZING FOR: {material['name']}\n" + "#"*80)

        scaler_path = os.path.join(RESULTS_DIR, f"{material['prefix']}_scaler.pkl")
        if not os.path.exists(scaler_path):
            print(f"ERROR: Cannot start visualization for {material['name']}.")
            print(f"Essential file '{scaler_path}' not found in {RESULTS_DIR}.")
            print("Please ensure CELL 1 ran successfully and all files are in the correct directory.")
            continue

        if 'true_optimum' not in material:
            print(f"CRITICAL ERROR: 'true_optimum' dictionary missing for {material['name']}.")
            if material['prefix'] == 'mgf2':
                 material['true_optimum'] = {'angle': 51.0, 'thickness': 148.0}
            elif material['prefix'] == 'sio2':
                 material['true_optimum'] = {'angle': 54.0, 'thickness': 150.0}
            print(f"Warning: Loaded true optimum parameters from hardcoded values as fallback: {material['true_optimum']}")

        # 1. Generate the main table for reviewers AND get the results dataframe
        results_df = create_and_save_results_table(material, all_loss_configs_for_reporting, all_custom_objects_for_reporting)

        if results_df is None or results_df.empty:
            print(f"Stopping visualization for {material['name']} due to missing results.")
            continue

        # 2. Generate the metric comparison bar chart (NEWLY ADDED)
        plot_metric_comparison_chart(material, results_df)

        # 3. Dynamically find the BEST model based on Validation MSE
        best_model_row = results_df.loc[results_df['MSE (Val, T_Error)'].idxmin()]
        best_model_name = best_model_row['Model']
        print("\n" + "*"*80)
        print(f"*** Best model for {material['name']} selected for detailed plots: {best_model_name} ***")
        print(f"*** Best Model Metrics (on T_Error): R²={best_model_row['R² (Val, T_Error)']:.4f}, MSE={best_model_row['MSE (Val, T_Error)']:.4f} ***")
        print("*"*80 + "\n")

        # 4. Generate the detailed plots *for the best model*
        generate_detailed_visualizations(material, all_custom_objects_for_reporting, best_model_name)

        # 5. Generate the final multi-model comparison plot (this one shows all models)
        plot_final_comparison(material, all_loss_configs_for_reporting)

    print("\n" + "="*80 + "\nCELL 2: VISUALIZATION & REPORTING COMPLETE.\n" + "="*80)
    # ==============================================================================
# ==============================================================================
#   REVISION ADD-ON  (RIO-D-26-00032R1)
#   Paste this ENTIRE block at the very END of LF.txt, AFTER the existing
#   "if __name__ == '__main__':" visualization loop (i.e. after line ~1034).
#
#   It RE-USES your already-trained .h5 models. NO retraining is required.
#   Run the whole file ONCE. New outputs land in RESULTS_DIR.
#
#   It produces, for BOTH materials:
#     (1) R3-C6  -> Non-learning baselines (Linear Interpolation + TMM Lookup)
#                  added to a new comparison table  *_baseline_vs_dl_table.csv/.png
#     (2) R3-C6  -> Full error analysis (MSE, RMSE, MAE, MaxAE) for all models
#                  *_full_error_analysis.csv
#     (3) R3-C7  -> A clean, publication-ready LaTeX version of Table I with
#                   correctly formatted numbers (fixes the "0.53.2" typo)
#                   *_table1_clean.tex
# ==============================================================================
# ==============================================================================
print("\n" + "="*80 + "\nSTARTING REVISION ADD-ON (reviewer response artifacts)\n" + "="*80)


def _load_split_for_addon(prefix, scaler):
    """Reproduce the exact train/val split (random_state=42) used everywhere else."""
    X_all, y_all, waves = load_dl_data_from_dir(f"{prefix}_data")
    if X_all is None or len(X_all) == 0:
        return None
    X_tr, X_val, y_tr, y_val = train_test_split(X_all, y_all, test_size=0.2, random_state=42)
    X_ood, y_ood, _ = load_dl_data_from_dir(f"{prefix}_ood_data")
    return {
        "X_tr": X_tr, "y_tr": y_tr,        # training pool (the 400 LHS pts)
        "X_val": X_val, "y_val": y_val,    # 100-sample validation
        "X_ood": X_ood, "y_ood": y_ood,    # 56-sample interpolative-grid (IG) test
        "waves": waves,
    }


def _nonlearning_baselines(split, method):
    """
    R3-C6: classical (non-deep-learning) surrogates fitted ONLY on the 400
    training samples, then evaluated on Val and IG sets. Operates on T_Error.
        method in {"linear", "nearest"}  ->  Linear Interp / TMM-style nearest lookup
    Returns dict of metrics on Val and IG, or None if a set is unavailable.
    """
    Xtr, ytr = split["X_tr"], split["y_tr"]

    def _predict(Xq):
        # Interpolate every spectral channel independently over the (angle, thickness) plane.
        out = np.empty((Xq.shape[0], ytr.shape[1]), dtype=np.float64)
        for ch in range(ytr.shape[1]):
            vals = _griddata(Xtr, ytr[:, ch], Xq, method=method)
            # points outside the training convex hull come back NaN -> fall back to nearest
            if np.any(np.isnan(vals)):
                nn = _griddata(Xtr, ytr[:, ch], Xq, method="nearest")
                vals = np.where(np.isnan(vals), nn, vals)
            out[:, ch] = vals
        return out

    res = {}
    for tag, Xk, yk in [("Val", split["X_val"], split["y_val"]),
                        ("IG",  split["X_ood"], split["y_ood"])]:
        if Xk is None or yk is None:
            res[tag] = None
            continue
        yp = _predict(Xk)
        res[tag] = {
            "R2":  r2_score(yk, yp),
            "MSE": mean_squared_error(yk, yp),
            "RMSE": float(np.sqrt(mean_squared_error(yk, yp))),
            "MAE": mean_absolute_error(yk, yp),
            "MaxAE": float(np.max(np.abs(yk - yp))),
        }
    return res


def _dl_full_errors(model, split):
    """Full error suite for one trained DL model, on Val and IG (T_Error domain)."""
    res = {}
    for tag, Xk, yk in [("Val", split["X_val"], split["y_val"]),
                        ("IG",  split["X_ood"], split["y_ood"])]:
        if Xk is None or yk is None:
            res[tag] = None
            continue
        # search_grid scaler was fit on raw (angle, thickness); reuse the SAME scaler
        yp = model.predict(split["_scaler"].transform(Xk), verbose=0)
        res[tag] = {
            "R2":  r2_score(yk, yp),
            "MSE": mean_squared_error(yk, yp),
            "RMSE": float(np.sqrt(mean_squared_error(yk, yp))),
            "MAE": mean_absolute_error(yk, yp),
            "MaxAE": float(np.max(np.abs(yk - yp))),
        }
    return res


def _fmt(x, nd=4):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "--"
    return f"{x:.{nd}f}"


def build_reviewer_artifacts(material_config, loss_configs, custom_objects):
    prefix = material_config["prefix"]
    scaler_path = os.path.join(RESULTS_DIR, f"{prefix}_scaler.pkl")
    if not os.path.exists(scaler_path):
        print(f"[add-on] No scaler for {prefix}; skipping.")
        return
    with open(scaler_path, "rb") as f:
        scaler = pickle.load(f)

    split = _load_split_for_addon(prefix, scaler)
    if split is None:
        print(f"[add-on] No data for {prefix}; skipping.")
        return
    split["_scaler"] = scaler

    # ---------------- (1) Non-learning baselines (R3-C6) ----------------
    rows = []
    for name, method in [("Linear Interpolation", "linear"),
                         ("TMM Nearest-Lookup", "nearest")]:
        m = _nonlearning_baselines(split, method)
        rows.append({
            "Method": name,
            "R2 (Val)": m["Val"]["R2"] if m["Val"] else np.nan,
            "MSE (Val)": m["Val"]["MSE"] if m["Val"] else np.nan,
            "R2 (IG)": m["IG"]["R2"] if m["IG"] else np.nan,
            "MSE (IG)": m["IG"]["MSE"] if m["IG"] else np.nan,
        })

    # ---------------- (2) Full error analysis for every DL model (R3-C6) ----------------
    err_rows = []
    for cfg in loss_configs:
        mp = os.path.join(RESULTS_DIR, f"{prefix}_model_{cfg['name']}.h5")
        if not os.path.exists(mp):
            continue
        lname = cfg["loss"].__name__ if callable(cfg["loss"]) else cfg["loss"]
        if cfg["name"] == "baseline_shape_only":
            lname = "focused_s100_v0_l0"
        elif cfg["name"] == "PROPOSED_Shape+Location_v2":
            lname = "focused_s95_v0_l5"
        co = {k: v for k, v in custom_objects.items() if k == lname}
        model = keras.models.load_model(mp, custom_objects=co, compile=False)
        fe = _dl_full_errors(model, split)
        v, g = fe["Val"], fe["IG"]
        err_rows.append({
            "Model": cfg["name"],
            "R2 (Val)": v["R2"] if v else np.nan,
            "MSE (Val)": v["MSE"] if v else np.nan,
            "RMSE (Val)": v["RMSE"] if v else np.nan,
            "MAE (Val)": v["MAE"] if v else np.nan,
            "MaxAE (Val)": v["MaxAE"] if v else np.nan,
            "R2 (IG)": g["R2"] if g else np.nan,
            "MSE (IG)": g["MSE"] if g else np.nan,
            "RMSE (IG)": g["RMSE"] if g else np.nan,
            "MAE (IG)": g["MAE"] if g else np.nan,
            "MaxAE (IG)": g["MaxAE"] if g else np.nan,
        })

    # Add the two non-learning baselines into the full error table too (Val/IG R2,MSE only)
    base_df = pd.DataFrame(rows)
    err_df = pd.DataFrame(err_rows)

    base_csv = os.path.join(RESULTS_DIR, f"{prefix}_baseline_vs_dl_table.csv")
    err_csv = os.path.join(RESULTS_DIR, f"{prefix}_full_error_analysis.csv")
    base_df.to_csv(base_csv, index=False)
    err_df.to_csv(err_csv, index=False)
    print(f"[add-on] Wrote {base_csv}")
    print(f"[add-on] Wrote {err_csv}")

    # ---------------- (3) Clean LaTeX Table I (R3-C7, fixes 0.53.2) ----------------
    # Pull the canonical Val/IG R2 & MSE for the models that appear in the paper's Table I.
    want = ["focused_s80_v10_l10", "focused_s90_v05_l05", "focused_s50_v25_l25",
            "baseline_mse", "baseline_l1_mae", "baseline_sam"]
    sub = err_df[err_df["Model"].isin(want)].set_index("Model").reindex(want)
    tex_lines = []
    pretty = {
        "focused_s80_v10_l10": r"\texttt{focused\_s80\_v10\_l10}",
        "focused_s90_v05_l05": r"\texttt{focused\_s90\_v05\_l05}",
        "focused_s50_v25_l25": r"\texttt{focused\_s50\_v25\_l25}",
        "baseline_mse": r"\texttt{baseline\_mse}",
        "baseline_l1_mae": r"\texttt{baseline\_l1\_mae}",
        "baseline_sam": r"\texttt{baseline\_sam}",
    }
    bold = {"focused_s80_v10_l10", "focused_s90_v05_l05"}
    for m in want:
        if m not in sub.index or sub.loc[m].isna().all():
            continue
        r = sub.loc[m]
        cells = [_fmt(r["R2 (Val)"]), _fmt(r["MSE (Val)"]),
                 _fmt(r["R2 (IG)"]), _fmt(r["MSE (IG)"])]
        label = pretty[m]
        if m in bold:
            label = r"\textbf{" + label + "}"
            cells = [r"\textbf{" + c + "}" for c in cells]
        tex_lines.append(label + " & " + " & ".join(cells) + r" \\")
    tex_path = os.path.join(RESULTS_DIR, f"{prefix}_table1_clean.tex")
    with open(tex_path, "w") as f:
        f.write(f"% Auto-generated clean Table I rows for {material_config['name']} (numbers verified)\n")
        f.write("\n".join(tex_lines) + "\n")
    print(f"[add-on] Wrote {tex_path}")

    # Console echo so you can copy numbers immediately
    print(f"\n----- {material_config['name']}: NON-LEARNING BASELINES (R3-C6) -----")
    print(base_df.to_string(index=False))
    print(f"\n----- {material_config['name']}: FULL ERROR ANALYSIS (R3-C6) -----")
    print(err_df.to_string(index=False))


# ---- run for both materials, reusing the configs already defined above ----
for _mat in all_material_configs:
    if "true_optimum" not in _mat:
        _mat["true_optimum"] = ({"angle": 51.0, "thickness": 148.0}
                                if _mat["prefix"] == "mgf2"
                                else {"angle": 54.0, "thickness": 150.0})
    build_reviewer_artifacts(_mat, all_loss_configs_for_reporting, all_custom_objects_for_reporting)

print("\n" + "="*80 + "\nREVISION ADD-ON COMPLETE.\n" + "="*80)

!zip -r all_my_results.zip . -x "sample_data/*"